name: Security Scan

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 1"  # weekly

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}